grafana:
  default: {}
  global:
    projects:
      console:
        envs:
          hprod:
            groups:
            - /admin
            - /admin
            tenants:
              hprod-dso: {}
          prod:
            groups:
            - /admin
            - /admin
            tenants:
              prod-dso: {}
        projectName: dso
        projectRepository:
          path: roles/gitops/rendering-apps-files/templates/dashboard
          url: https://github.com/cloud-pi-native/socle.git
  grafana:
    adminPassword: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#grafana|
      jsonPath {.adminPassword}>
    isOpenShift: false
    observatorium_url: https://<path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain
      | jsonPath {.observatorium}>
  grafana-operator:
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: operator
                app.kubernetes.io/instance: gcp-dev-dso-grafana
                app.kubernetes.io/name: grafana-operator
            topologyKey: kubernetes.io/hostname
          weight: 100
  grafanaNamespace: dso-grafana
  oauth:
    aud: grafana
    enabled: true
    groups_attribute_path: group
    id: <path:dso-gcp-dev/data/env/conf-dso/apps/keycloak/values#client | jsonPath
      {.grafana.id}>
    scopes: profile, email, openid, group
    secret: <path:dso-gcp-dev/data/env/conf-dso/apps/keycloak/values#client | jsonPath
      {.grafana.secret}>
    url: https://<path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain | jsonPath
      {.keycloak}>/realms/dso
  server:
    certManager:
      enabled: true
    ingressClassName: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#ingressClassName>
    url: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain | jsonPath
      {.grafana}>
observatorium:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: api
              app.kubernetes.io/instance: gcp-dev-dso-observatorium
              app.kubernetes.io/name: observatorium
          topologyKey: kubernetes.io/hostname
        weight: 100
  api:
    config:
      clientID: account
      groupClaim: groups
      groups:
      - /admin
      id: prod-infra
      issuerURL: https://<path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain
        | jsonPath {.keycloak}>/realms/dso
      name: prod-infra
      usernameClaim: preferred_username
    loglevel: info
  global:
    projects:
      console:
        envs:
          hprod:
            groups:
            - /admin
            - /admin
            tenants:
              hprod-dso: {}
          prod:
            groups:
            - /admin
            - /admin
            tenants:
              prod-dso: {}
        projectName: dso
        projectRepository:
          path: roles/gitops/rendering-apps-files/templates/dashboard
          url: https://github.com/cloud-pi-native/socle.git
  ingress:
    enabled: true
    hosts:
    - host: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain | jsonPath
        {.observatorium}>
      paths:
      - path: /
        pathType: ImplementationSpecific
    ingressClassName: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#ingressClassName>
    tls:
    - hosts:
      - <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain | jsonPath {.observatorium}>
      secretName: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain |
        jsonPath {.observatorium}>-tls
  logs:
    enabled: false
    read:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.logs}>
    rules:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.logs}>
    tail:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.logs}>
    write:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.logs}>
  metrics:
    alertmanager:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.metrics}>
    enabled: false
    read:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.metrics}>
    rules:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.metrics}>
    tenantHeader: X-Scope-OrgId
    write:
      endpoint: <path:dso-gcp-dev/data/env/conf-dso/apps/observability/values#endpoint
        | jsonPath {.metrics}>
