kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: keycloak
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  admin-password: <path:dso-s3ns-dev/data/env/conf-dso/apps/keycloak/values#auth | jsonPath {.adminPassword} | base64encode>
