apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-users
  namespace: dso-keycloak
data:
  users.csv: |
    username,surname,name,email,status
    admin@example.com,Admin,Admin,admin@example.com,active
