---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-vault-infra-secret
  namespace: infra-vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["list", "get"]
