kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: sonarqube
  annotations:
    avp.kubernetes.io/remove-missing: "true"
data:
  password: <path:dso-s3ns-dev/data/env/conf-dso/apps/sonarqube/values#auth | jsonPath {.adminPassword} | base64encode>
  currentPassword: YWRtaW4=
