---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: s3ns-dev-dso-install-manager-wave-40
  namespace: infra-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  ignoreApplicationDifferences:
    - jqPathExpressions:
        - .spec.source.plugin.env[] | select(.name == "HELM_VALUES").value
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/benji78/pi-native-socle.git
              revision: gitops
              files:
                - path: "gitops/envs/conf-dso/conf-dso.json"
              requeueAfterSeconds: 10 # Polling interval for health_status (seconds)
          - list:
              elementsYaml: "{{ .apps | toJson }}"
            selector:
              matchExpressions:
                - key: enabled
                  operator: In
                  values:
                    - "true"
                - key: syncWave
                  operator: In
                  values: ["40"]
  template:
    metadata:
      name: "s3ns-dev-{{.namespacePrefix}}{{.app}}"
      annotations:
        argocd.argoproj.io/compare-options: ServerSideDiff=true
      labels:
        platform.env: "{{.env}}"
        platform.provider: "{{.provider}}"
        platform.region: "{{.region}}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      revisionHistoryLimit: 3
      source:
        repoURL: https://github.com/benji78/pi-native-socle.git
        path: "gitops/envs/{{.env}}/apps/{{.app}}"
        targetRevision: "{{.targetRevision}}"
        plugin:
          env:
            - name: AVP_SECRET
              value: vault-plugin-secret
            - name: HELM_ARGS
              value: -f values.yaml
            - name: HELM_VALUES
              value: |
                destinationClusterName: {{.destination.clusterName}}
      destination:
        name: "{{ default .destination.clusterName .clusterName }}"
        namespace: "{{ default .namespacePrefix .customNamespacePrefix }}{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
        #  selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
  syncPolicy:
    preserveResourcesOnDeletion: true
    # automated:
    #   selfHeal: true
