cloudnativepg:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: cloudnative-pg
              app.kubernetes.io/name: cloudnative-pg
          topologyKey: kubernetes.io/hostname
        weight: 100
  fullnameOverride: cloudnative-pg
  image:
    registry: <path:dso-s3ns-dev/data/env/conf-dso/apps/global/values#image | jsonPath
      {.repository.ghcr}>/cloudnative-pg/cloudnative-pg
  nameOverride: cloudnative-pg
  replicaCount: 3
