cpn-ansible-job:
  cronJob:
    create: true
  job:
    annotations:
      argocd.argoproj.io/hook: Sync
    command:
    - /bin/sh
    - -c
    - 'git clone https://github.com/cloud-pi-native/socle.git && \

      cd socle && \

      ansible-playbook post-install/vault.yaml

      '
    extraEnvFrom:
    - secretRef:
        name: ansible-secret
    image:
      repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image | jsonPath
        {.repository.ghcr}>/cloud-pi-native/git-ansible
      tag: '1'
vault:
  csi:
    agent:
      image:
        repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image |
          jsonPath {.repository.docker}>/hashicorp/vault
    image:
      repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image | jsonPath
        {.repository.docker}>/hashicorp/vault-csi-provider
  fullnameOverride: conf-dso-vault
  injector:
    agentImage:
      repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image | jsonPath
        {.repository.docker}>/hashicorp/vault
    image:
      repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image | jsonPath
        {.repository.docker}>/hashicorp/vault-k8s
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - ALL
      pod:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 100
  server:
    auditStorage:
      enable: true
    dataStorage:
      enable: true
      size: 23Gi
    ha:
      apiAddr: https://<path:dso-gcp-dev/data/env/conf-dso/apps/global/values#domain
        | jsonPath {.vault}>
      enabled: true
      raft:
        enabled: true
      replicas: 3
    image:
      repository: <path:dso-gcp-dev/data/env/conf-dso/apps/global/values#image | jsonPath
        {.repository.docker}>/hashicorp/vault
    route:
      enabled: false
    standalone:
      enabled: false
    statefulSet:
      securityContext:
        container:
          allowPrivilegeEscalation: false
        pod:
          fsGroup: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 100
