apiVersion: v2
dependencies:
- alias: cluster
  name: cluster
  repository: https://cloudnative-pg.io/charts
  version: 0.3.1
- alias: sonarqube
  name: sonarqube
  repository: https://sonarsource.github.io/helm-chart-sonarqube
  version: 10.8.1
- alias: cpn-ansible-job
  name: cpn-job
  repository: https://cloud-pi-native.github.io/helm-charts
  version: '>=1.0.0 <2.0.0'
name: sonarqube
type: application
version: 10.8.1
